/* Generate the /worldcup/-scoped service worker (sw.js) so the Hub works fully
   OFFLINE. Zero dependencies. Run from the worldcup/ folder: `node build-pwa.js`.

   IMPORTANT: run this AFTER make-offline.sh, so the vendored libs/flags/fonts and
   offline-config.js exist and get precached. The deploy script sequences this.

   The worker is self-contained at /worldcup/sw.js → scope /worldcup/, so it does
   NOT collide with the arcade's root worker (longest-matching-scope wins, and the
   Hub loads nothing cross-folder). It serves cache-first (stale-while-revalidate)
   and matches ignoring ?v= query strings (the Hub cache-busts its scripts that way),
   so a versioned request still hits the precached file offline. live-scores.json is
   precached (last-known scores offline) and refreshed from the network when online. */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = __dirname;
const URL_PREFIX = '/worldcup';

const CACHE_EXT = new Set(['.html', '.js', '.jsx', '.css', '.json', '.woff2', '.woff', '.ttf', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico']);
// Skip dev/build/test/print artefacts and anything with spaces (the standalone print pages).
function skip(name, rel) {
  if (/\s/.test(name)) return true;                       // "World Cup 2026 Bracket.html" etc.
  if (/^\./.test(name)) return true;                       // dotfiles
  if (name === 'sw.js') return true;                       // never cache the worker itself
  if (/^(build-|make-offline|deploy-|start\.)/.test(name)) return true;
  if (/\.(test|spec)\.js$/.test(name)) return true;
  if (/\.(bak|py|pyc|gs|md|sh|bat|command)$/.test(name)) return true;
  if (/\.example\.json$/.test(name)) return true;
  if (/(^|\/)(node_modules|__pycache__|screenshots|docs|\.git)(\/|$)/.test(rel)) return true;
  return false;
}

function walk(absDir, rel, acc, hash) {
  for (const entry of fs.readdirSync(absDir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const childRel = rel ? rel + '/' + entry.name : entry.name;
    if (skip(entry.name, childRel)) continue;
    const abs = path.join(absDir, entry.name);
    if (entry.isDirectory()) { walk(abs, childRel, acc, hash); continue; }
    if (!CACHE_EXT.has(path.extname(entry.name).toLowerCase())) continue;
    const url = URL_PREFIX + '/' + childRel;
    acc.push(url);
    hash.update(url);
    hash.update(fs.readFileSync(abs));
  }
}

const urls = [];
const hash = crypto.createHash('sha256');
walk(ROOT, '', urls, hash);
// The Hub navigates to the folder root; make sure the directory URL resolves offline.
if (!urls.includes(URL_PREFIX + '/index.html')) urls.push(URL_PREFIX + '/index.html');
urls.push(URL_PREFIX + '/');
urls.sort();
const version = hash.digest('hex').slice(0, 10);

const sw = `/* AUTO-GENERATED by build-pwa.js — do not edit by hand.
   /worldcup/-scoped service worker for the World Cup 2026 Family Hub.
   Precaches every Hub asset so it runs with NO network once installed. */
const CACHE = 'wc26-hub-${version}';
const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Individually so one renamed/missing file can't abort the whole precache.
    await Promise.allSettled(PRECACHE.map((u) => cache.add(new Request(u, { cache: 'reload' }))));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE && key.startsWith('wc26-hub-')) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;        // ignore cross-origin
  if (!url.pathname.startsWith('/worldcup/')) return;      // stay in our scope

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    // ignoreSearch so the Hub's ?v=... cache-busted scripts still hit the precache.
    const cached = await cache.match(req, { ignoreSearch: true });
    const fromNetwork = fetch(req).then((res) => {
      if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
      return res;
    }).catch(() => null);

    if (cached) { event.waitUntil(fromNetwork); return cached; }
    const net = await fromNetwork;
    if (net) return net;

    if (req.mode === 'navigate') {
      const shell = await cache.match('/worldcup/index.html', { ignoreSearch: true });
      if (shell) return shell;
    }
    return new Response('Offline — open the Hub once on Wi-Fi first.', { status: 503, headers: { 'Content-Type': 'text/plain' } });
  })());
});

self.addEventListener('message', (e) => { if (e.data === 'skip-waiting') self.skipWaiting(); });
`;

fs.writeFileSync(path.join(ROOT, 'sw.js'), sw);
console.log('✓ worldcup/sw.js written — cache ' + version + ', ' + urls.length + ' precached assets.');
